---
title: "Briggsdale"
author: "Rachel Havranek"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged # omit to disable paged data table output
    number_sections: yes # change to no for unnumbered sections
    toc: yes # change to no to disable table of contents
    toc_float: true # change to false to keep toc at the top
    toc_depth: 3 # change to specify which headings to include in toc
    code_folding: show # change to hide to hide code by default
editor_options:
  chunk_output_type: console
---
# Setup
```{r setup, echo = TRUE, message=FALSE, warning=FALSE}
## load libraries
library(tidyverse) 
library(latex2exp)
library(viridis)
library(data.table)
library (lubridate)
library(plotly)
library(fs)
library(gridExtra)
library(egg)

setwd("/Volumes/Havranek External Hard Drive /NSF EAR 2023385/QAQC_bySWISS/SWISS_QAQC/")

# source all relevant scripting files
source(file.path ("scripts", "plotting_functions.R"))
source(file.path ("scripts", "PicarroData_BreakUp.R"))
source(file.path ("scripts", "Rachels_custom_plots.R"))
source(file.path("scripts", "corrections.R"))

# global knitting options for automatic saving of all plots as .png and .pdf
knitr::opts_chunk$set(
  dev = c("png", "pdf"), fig.keep = "all",
  dev.args = list(pdf = list(encoding = "WinAnsi", useDingbats = FALSE)),
  fig.path = file.path("fig_output", paste0(gsub("\\.[Rr]md", "", knitr::current_input()), "_"))
)
```

```{r load data}
tbl <- readRDS(file.path("data", "2021Data.RDS")) %>% 
  bind_rows(readRDS(file.path("data","2022Data.RDS")))
```

# First deployment
## August 10, 2022
```{r}
data_0810 <- tbl %>% 
  filter (DATE == "2022-08-10") %>% 
  BoulderTime() %>% 
  filter(MDT > "2022-08-10 13:30" & MDT < "2022-08-10 18:00") %>% 
  h2o_batches() %>% 
  filter (H2O_Batch == 22 | H2O_Batch == 46 | H2O_Batch == 102 | H2O_Batch == 329 | H2O_Batch == 359 | H2O_Batch == 388)

h2o_batch_plt(data_0810)
d180_time_plt(data_0810)
h2O_FirstThreeMinutes(data_0810)

flasks_0810 <- data_0810 %>% 
  flask_first3minutes() %>% 
  mutate(
    Flask = c(16:11),
    sampledate = ifelse(Flask > 13, "2022-08-06", "2022-08-01"),
    sampledepth = c(75,50,25,75,50,25),
    Analyst = "Haley"
  )
```

## August 11 
```{r}
data_0811 <- tbl %>% 
  filter(DATE == "2022-08-11") %>% 
  BoulderTime() %>% 
  filter(MDT > "2022-08-11 11:00" & MDT < "2022-08-11 14:13:30") %>% 
  h2o_batches() %>% 
  filter(H2O >5000)

h2o_batch_plt(data_0811)
h2O_FirstThreeMinutes(data_0811)

flasks_0811 <- data_0811 %>% 
  flask_first3minutes() %>% 
  mutate(
    Flask = c(10:5),
    sampledate = ifelse (Flask >7 & Flask < 11, "2022-07-27", "2022-07-22"),
    sampledepth = c(75,50,25,75,50,25),
    Analyst = "Haley"
  )
```

## August 12, 2022
```{r}
data_0812 <- tbl %>% 
  filter(DATE == "2022-08-12") %>% 
  BoulderTime() %>% 
  filter(MDT > "2022-08-12 12:21" & MDT < "2022-08-12 13:53") %>% 
  h2o_batches() %>% 
  filter(H2O > 5000)

h2o_batch_plt(data_0812)
d180_time_plt(data_0812)
h2O_FirstThreeMinutes(data_0812)

flasks_0812 <- data_0812 %>% 
  flask_first3minutes() %>% 
    mutate(
        Flask = c(4:2),
        sampledate = "2022-07-17",
        sampledepth = c(75,50,25),
        Analyst = "Haley"
    )
```

```{r}
Brigssdale_july2022 <- bind_rows(flasks_0810,flasks_0811,flasks_0812) %>%
 
  mutate(
    T = 23, #estimate until we dig up the loggers
     #transfer to liquid values
    d18O_liq = round((11.45 - 0.0795*T +1.0012*d18O_out),1),
    d2H_liq =round((104.96 - 1.0342*T + 1.0724*d2H_out),1),
    
    #transfer to VSMWOW
    d18O_corr = round(( (d18O_liq - 0.3055)/1.005),1),
    dD_corr = round(( (d2H_liq - -9.5209)/0.9878),1),
    
    # apply swiss offset correction
    d18o_offset = d18O_corr - 1.0,
    dD_offset = dD_corr - 2.6,
    
    dexcess = dD_offset - 8*d18o_offset
  ) 
```


```{r}
# Brigssdale_july2022 <- Brigssdale_july2022 %>% 
#   mutate(
#     d18O_off_first = d18O_out - 1.0,
#     dD_off_first = d2H_out - 2.6, 
#     
#     d18O_thenroth = round((11.45 - 0.0795*T +1.0012*d18O_off_first),1),
#     d2H_thenroth = round((104.96 - 1.0342*T + 1.0724*dD_off_first),1),
#     
#     vsmow_last_d180 = round(( (d18O_thenroth - 0.3055)/1.005),1),
#     vsmow_last_d2H = round(( (d2H_thenroth - -9.5209)/0.9878),1)
#   )
```


```{r}
Brigssdale_july2022_plt <- Brigssdale_july2022 %>%   
  filter(sampledepth > 25) %>% 
  ggplot()+
  ylab(latex2exp::TeX('$\\delta^{18}O VSMOW$'))+
  ggtitle("Briggsdale, CO")+
  geom_errorbar(aes(
    x = sampledate,
    ymax = d18o_offset - 0.9,
    ymin = d18o_offset + 0.9,
    width = 0)) +
  geom_point(
    aes(
      x= sampledate,
      y = d18o_offset,
      pch = as.factor(sampledepth),
      fill = as.factor(sampledepth)
    ),
    size = 6
  ) +
  scale_shape_manual(values = c(23,24), name = "Sample Depth (cm)") +
  scale_fill_manual(values = c("#20908C", "#FCE621"), name = "Sample Depth (cm)")+
  theme_figure() +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  )

Brigssdale_july2022_plt
```

```{r}
Brigssdale_d2h <- Brigssdale_july2022 %>% 
  filter(sampledepth > 25) %>% 
  ggplot()+
  ylab(latex2exp::TeX('$\\delta^2H VSMOW$'))+
  geom_errorbar(aes(
    x = sampledate,
    ymax = dD_offset - 3.6,
    ymin = dD_offset + 3.6,
    width = 0)) +
  geom_point(
    aes(
      x= sampledate,
      y = dD_offset,
      pch = as.factor(sampledepth),
      fill = as.factor(sampledepth)
    ),
    size = 6
  ) +
  scale_shape_manual(values = c(23,24), name = "Sample Depth (cm)") +
  scale_fill_manual(values = c("#20908C", "#FCE621"), name = "Sample Depth (cm)")+
  theme_figure() +
  theme(
    axis.text.x = element_text(size = 14, angle = 45,  hjust=1),
    axis.title.x = element_blank(),
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14)
  )

print(Brigssdale_d2h)
```

```{r Briggsdale june data}
ggarrange(Brigssdale_july2022_plt, Brigssdale_d2h)

Brigssdale_july2022 %>% 
  filter(sampledepth > 25) %>% 
  mutate(
    Site = "Briggsdale"
  ) %>% 
    dplyr::select(Site, sampledate, sampledepth, Flask, T, d18o_offset, SD_18O_out, dD_offset, SD_2H_out) %>% 
      arrange(Flask) %>% 
        rename(Date = sampledate, Depth = sampledepth, AnalyticalError = SD_18O_out) %>% 
        write.csv("output/BriggsdaleJulyData.csv")
```


```{r}
crossplt <- Brigssdale_july2022 %>% 
  filter(sampledepth > 25) %>% 
  ggplot()+
  geom_errorbar(aes(
    x = d18o_offset,
    ymax = dD_offset - 3.6,
    ymin = dD_offset + 3.6,
    width = 0)) +
  geom_errorbarh(aes(
    y = dD_offset,
    xmax = d18o_offset - 0.9,
    xmin = d18o_offset + 0.9,
    height = 0)) +
  geom_point(
    aes(
      x = d18o_offset, 
      y = dD_offset, 
      pch = factor(sampledepth),
      fill = factor(sampledate)),
    size = 6
  )+
  scale_shape_manual(values = c(23,24), name = "Sample Depth (cm)") +
  scale_fill_viridis(discrete = TRUE, name = "Sample Date") +
  ylab(latex2exp::TeX('$\\delta^2H (VSMOW)$'))+
  xlab(latex2exp::TeX('$\\delta^{18}O (VSMOW)$')) +
  theme_figure()

crossplt
```

```{r}
B_dexcess <- Brigssdale_july2022 %>% 
  filter(sampledepth > 25) %>% 
  ggplot()+
  ylab("d-excess")+
  xlab("Sample Date")+
  geom_point(
    aes(
      x= sampledate,
      y = dexcess,
      pch = as.factor(sampledepth),
      fill = as.factor(sampledepth)
    ),
    size = 6
  ) +
  scale_shape_manual(values = c(23,24), name = "Sample Depth (cm)") +
  scale_fill_manual(values = c("#20908C", "#FCE621"), name = "Sample Depth (cm)")+
  theme_figure()+
  #scale_y_continuous(breaks=c(-62, -58, -54))+
  theme(
    axis.text.x = element_text(size = 14, angle = 45,  hjust=1),
    axis.title.x = element_blank(),
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14)
  )

print(B_dexcess)
```


```{r}
poop <- ggarrange(Brigssdale_july2022_plt, Brigssdale_d2h, B_dexcess)

ggsave( "poop.png", poop)
```

```{r}
latex2exp::latex2exp_supported(
)
```




