---
title: "QAQC of Raclette"
author: "Rachel Havranek"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged # omit to disable paged data table output
    number_sections: yes # change to no for unnumbered sections
    toc: yes # change to no to disable table of contents
    toc_float: true # change to false to keep toc at the top
    toc_depth: 3 # change to specify which headings to include in toc
    code_folding: show # change to hide to hide code by default
editor_options:
  chunk_output_type: console # change to inline to show output inline
---

#Setup
```{r setup, echo = TRUE, message=FALSE, warning=FALSE}
# load libraries
library(tidyverse) 
library(latex2exp)
library(viridis)
library(data.table)
library (lubridate)
library(plotly)
library(fs)

setwd("/Volumes/Havranek External Hard Drive /NSF EAR 2023385/QAQC_bySWISS/SWISS_QAQC/")

# source all relevant scripting files
source(file.path ("scripts", "plotting_functions.R"))
source(file.path ("scripts", "flask_ave.R"))
source(file.path ("scripts", "Eriks_functions.R"))
source(file.path ("scripts", "outlet_cut_functions.R"))
source(file.path ("scripts", "Rachels_custom_plots.R"))

# global knitting options for automatic saving of all plots as .png and .pdf
knitr::opts_chunk$set(
  dev = c("png", "pdf"), fig.keep = "all",
  dev.args = list(pdf = list(encoding = "WinAnsi", useDingbats = FALSE)),
  fig.path = file.path("fig_output", paste0(gsub("\\.[Rr]md", "", knitr::current_input()), "_"))
)

#load data
tbl <- readRDS(file.path("data", "2021Data.RDS"))
```

# Dry Air 1, July 27, 2021

```{r}
data_072721 <- tbl %>% 
  filter(DATE == "2021-07-27") %>% 
    mutate(UTC = hms(TIME), #by using the lubridate hms, it makes the UTC time filterable with dplyr
           UTC_full = with_tz(ymd_hms(paste(DATE, TIME)), tzone = "UTC"), 
           MDT = with_tz(UTC_full, tzone = "America/Denver"),
           seconds = row_number()) %>% 
      filter(MDT > "2021-07-27 09:35:00" & MDT < "2021-07-27 11:14:19" ) %>% 
  outlet_batches()

WaterConcentration_plt(data_072721)
plt_outlet_batch(data_072721)

flask_aves_072721 <- data_072721 %>% 
  flask_ave_outlet() %>% 
  filter(batch != 11) %>% 
  mutate(Flask = c(2:9, 11:15))


#Manually separate flasks 10, 12, 16 
manual_flasks_072721 <- data_072721 %>% 
  filter (MDT > "2021-07-27 10:27:18" & MDT <"2021-07-27 10:34:00") %>% 
  flask_ave_outlet() %>% 
  mutate(Flask = 10)

manual_flasks_072721 <- manual_flasks_072721 %>% 
  bind_rows(
    data_072721 %>% 
  filter (MDT > "2021-07-27 11:06:49" & MDT <"2021-07-27 11:14:11") %>% 
  flask_ave_outlet() %>% 
  mutate(Flask = 16)
  )

flask_aves_072721 <- flask_aves_072721 %>% 
  bind_rows(manual_flasks_072721)


Flask_h2o_plt(flask_aves_072721)
```


# Water Vapor, August 1 - August 18, 2021 
 **INPUT VALUES**
 Here, I just picked three peaks, all about an hour apart, averaged their value for the last 2 minutes of filling. After seeing they were all well within error of each other, I averaged them and that's what I'm calling my 'input' value. 
```{r input values}
data_080121 <- tbl %>% 
  filter(DATE == "2021-08-01") %>% 
    mutate(UTC = hms(TIME), #by using the lubridate hms, it makes the UTC time filterable with dplyr
           UTC_full = with_tz(ymd_hms(paste(DATE, TIME)), tzone = "UTC"), 
           MDT = with_tz(UTC_full, tzone = "America/Denver"),
           seconds = row_number())  %>% 
      filter(MDT > "2021-08-01 13:52:00") 

WaterConcentration_plt(data_080121)
OutletValve_plt(data_080121)


inputvalue1 <- data_080121 %>% 
  filter(MDT > "2021-08-01 16:07:26" & MDT < "2021-08-01 16:09:26") %>% 
  flask_out_ave()
  

inputvalue1 <- inputvalue1 %>% 
  bind_rows(
    data_080121 %>% 
  filter(MDT > "2021-08-01 15:24:30" & MDT < "2021-08-01 15:26:30") %>% 
  flask_out_ave()
  )

inputvalue1 <- inputvalue1 %>% 
  bind_rows(
    data_080121 %>% 
  filter(MDT > "2021-08-01 17:20:00" & MDT < "2021-08-01 17:22:00") %>% 
  flask_out_ave()
  )

d18O_in_0801 <- round(mean(inputvalue1$d18O_out),2)
SD_d18O_in <- round(mean(inputvalue1$SD_18O_out),2)
d2H_in_0801 <- round(mean(inputvalue1$d2H_out),2)
SD_d2H_in <- round(mean(inputvalue1$SD_2H_out ),2)
```

```{r}
data_080121 <- tbl %>% 
  filter(DATE == "2021-08-01") %>% 
    mutate(UTC = hms(TIME), #by using the lubridate hms, it makes the UTC time filterable with dplyr
           UTC_full = with_tz(ymd_hms(paste(DATE, TIME)), tzone = "UTC"), 
           MDT = with_tz(UTC_full, tzone = "America/Denver"),
           seconds = row_number())
```



# Dry Air 2, August 25 - September 1, 2021 

