---
title: "Seibert SWISS data"
author: "Rachel Havranek"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged # omit to disable paged data table output
    number_sections: yes # change to no for unnumbered sections
    toc: yes # change to no to disable table of contents
    toc_float: true # change to false to keep toc at the top
    toc_depth: 3 # change to specify which headings to include in toc
    code_folding: show # change to hide to hide code by default
editor_options:
  chunk_output_type: console
---
# Set up 
```{r setup, echo = TRUE, message=FALSE, warning=FALSE}
# load libraries
library(tidyverse) 
library(dplyr)
library(latex2exp)
library(viridis)
library(data.table)
library (lubridate)
library(plotly)
library(fs)

setwd("/Volumes/Havranek External Hard Drive /NSF EAR 2023385/QAQC_bySWISS/SWISS_QAQC/")

# source all relevant scripting files
source(file.path ("scripts", "plotting_functions.R"))
source(file.path ("scripts", "PicarroData_BreakUp.R"))
source(file.path ("scripts", "Rachels_custom_plots.R"))

# global knitting options for automatic saving of all plots as .png and .pdf
knitr::opts_chunk$set(
  dev = c("png", "pdf"), fig.keep = "all",
  dev.args = list(pdf = list(encoding = "WinAnsi", useDingbats = FALSE)),
  fig.path = file.path("fig_output", paste0(gsub("\\.[Rr]md", "", knitr::current_input()), "_"))
)

#load data
# tbl <-
#     list.files ("data/Data2022", pattern = "*.dat", recursive = T, full.names = T) %>%
#     map_df(~read_table2(.)) %>%
#     as_tibble() %>%
#     dplyr::select(1, 2, 15, 17, 18, 19)   
# 
# saveRDS(tbl, "data/2022Data.RDS")


tbl <- readRDS(file.path("data", "2021Data.RDS")) %>% 
  bind_rows(readRDS(file.path("data","2022Data.RDS")))
```

# July 18 & July 19 data

11, 12, 13 were 4th of July samples
8,9,10 were June 29th samples 
5,6,7 were June 24th samples
2,3,4 were June 19th samples 


flask 13 is messy  - averaging over a 9 minute window to represent real variability. Did a dead end pull to dry air at 30 ml/ min at 13:10. 

flask 11 - condensation has a problem 

```{r}
data_071822_firstbatch <- tbl %>% 
  filter (DATE == "2022-07-18" | DATE == "2022-07-2") %>% 
  BoulderTime() %>% 
  filter (MDT > "2022-07-18 13:00:00" & MDT < " 2022-07-18 16:00:00") %>% 
  h2o_batches() 


flask13 <- data_071822_firstbatch %>% 
  filter (MDT > "2022-07-18 13:09:00" & MDT < "2022-07-18 13:16:00") %>% 
  flask_out_ave() %>% 
  mutate(Flask = 13)

flask11 <-  data_071822_firstbatch %>% 
  filter (MDT > "2022-07-18 13:52:00" & MDT < "2022-07-18 13:55:00") %>% 
  flask_out_ave() %>% 
  mutate(Flask = 11)


Flasks071822 <-  data_071822_firstbatch %>% 
  filter(H2O_Batch == 88 | H2O_Batch == 181 | H2O_Batch == 226 | H2O_Batch == 271) %>% 
  flask_first3minutes %>% 
  mutate(Flask = c(12,10,9,8)) %>% 
  bind_rows(flask13, flask11) %>% 
  mutate(sampledate = ifelse(Flask > 10, "22-07-04", "22-06-29"))
```

evening work
```{r}
data_071822_secondbatch <- tbl %>% 
  filter (DATE == "2022-07-19") %>% 
  BoulderTime() %>% 
  filter (MDT > "2022-07-18 13:00:00" & MDT < " 2022-07-18 16:00:00") %>% 
  h2o_batches() 
```



